export_languages: ["en-GB"]
files:
  - source: /admin/language/en-GB/**/*.php
    translation: /admin/**/%original_file_name%
    update_option: update_as_unapproved
  - source: /admin/language/en-GB/*.php
    translation: /admin/%original_file_name%
    update_option: update_as_unapproved
  - source: /catalog/language/en-GB/**/*.php
    translation: /catalog/**/%original_file_name%
    update_option: update_as_unapproved
  - source: /catalog/language/en-GB/*.php
    translation: /catalog/%original_file_name%
    update_option: update_as_unapproved
  - source: /install/language/en-GB/*.php
    translation: /install/%original_file_name%
    update_option: update_as_unapproved
