export_languages: ["en-GB"]
files:
  - source: /admin/language/en-GB/**/*.php
    translation: /admin/language/%locale%/**/%original_file_name%
    update_option: update_as_unapproved
  - source: /admin/language/en-GB/*.php
    translation: /admin/language/%locale%/%original_file_name%
    update_option: update_as_unapproved
  - source: /catalog/language/en-GB/**/*.php
    translation: /catalog/language/%locale%/**/%original_file_name%
    update_option: update_as_unapproved
  - source: /catalog/language/en-GB/*.php
    translation: /catalog/language/%locale%/%original_file_name%
    update_option: update_as_unapproved
  - source: /install/language/en-GB/*.php
    translation: /install/language/%locale%/%original_file_name%
    update_option: update_as_unapproved
