export_languages: ["en-GB"]
files:
  - source: /admin/language/en-GB/*/*.php
    translation: /admin/language/%locale%/*/%original_file_name%
    translation_replace:
      en-GB.:
    update_option: update_as_unapproved
    
